package com.example.mighty.airtelapp.apirequest;

import com.example.mighty.airtelapp.model.Feed;
import com.example.mighty.airtelapp.model.RequestBody;
import com.example.mighty.airtelapp.model.ResponseBody;

import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.Headers;
import retrofit2.http.POST;

public interface APIInterface {

    String BASE_URL = "http://phplaravel-116401-370897.cloudwaysapps.com/";

    @Headers("Content-Type: application/json")
    @GET("api/admin/data_request")
    Call<Feed> getData();

    @Headers("Authorization: Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjY0NTFkMGVhZjE5MDcxMzE5NzczNjI0NGVhYmUxYWQ4NmM0M2E0ZjAxNjJkZjM3NjAyMWZhMDc0NDJjODA3MTQ2OTY0ZTBlZDBmZTNjMGUwIn0.eyJhdWQiOiIxIiwianRpIjoiNjQ1MWQwZWFmMTkwNzEzMTk3NzM2MjQ0ZWFiZTFhZDg2YzQzYTRmMDE2MmRmMzc2MDIxZmEwNzQ0MmM4MDcxNDY5NjRlMGVkMGZlM2MwZTAiLCJpYXQiOjE1Mjg3MTgyNjIsIm5iZiI6MTUyODcxODI2MiwiZXhwIjoxNTYwMjU0MjYyLCJzdWIiOiIxMTIiLCJzY29wZXMiOltdfQ.H2atTes33gwslzGiL2H6xn6qxuRpJaWs5DBoEw7cgArI02k7l7xLPdylouadwxTTn0KW7AVS5dMN-bbOASxgAjkkS-VDXkTWAC4s-2phXIYvoNQdl7Um8lW5N8GCIiOTiFs8l4PmBf39neVipMydyecv_h2g2TwUd9TCH6oF92NDIPdr6_bqh9Tr9wVb1O59TatTDTCWYoolde3bZuRHwQ401q3fWToNzEEeO2RpsLFGCxvZ40aGOlB54DX3JaL-EsPy-tgWgfba2L0R7NREXfXQPxz4mKNM0zzC6Q8fk-tzU692dfvXolXmx99Ld6Y0dlgYNx3hGXMqeTxsE_jeNqucfu24b7I7dTxJc5GyKdwNyNndizITcPUsI5PjOM0fcF_NopkBP8yowIi4sVsNIt9P2wbqExT1cA_U_AQ4CPVNlEGkczNogvGjPTTNdp3j9IjINpCIAejAltPihT_Ck89sTtNjAkek3VXGcRcb_0ZkJwwGmyQdSz9rpJQfxAuyli_8roRbBkO1O7-uQBRjTVwU2dk4toatNRVahvXPzpUS8H9CnYz5u03uCH3jKJvfubqxRC2H306c784jU64cihwhBtc4y_oy1SmpWIhECxGOtaOKJcNKy2jeRQb9Vz3c8hUW09b6Hn9YeQDFYUR9xRwktSrUHqZXbs1D-r247OE")
    @POST("api/admin/data_request")
    Call<ResponseBody> postToken(@Body RequestBody requestBody);
}
